---
resources:
- name: repo
  type: git
  source: 
    uri: 'https://github.com/yuichi10/pcf-app.git'
    branch: master
  check_every: 1200h
- name: pcf
  type: cf
  source:
    api: 'https://api.local.pcfdev.io'
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-org))
    space: ((pcf-space))
    skip_cert_check: true
jobs:
- name: go-test
  plan:
  - get: repo
    trigger: true
  - task: unit-test
    file: repo/ci/unit-test.yml
- name: deploy
  serial: true
  plan:
  - get: repo
    passed: [go-test]
    trigger: true
  - task: prepare-build
    file: repo/ci/build.yml
  - put: pcf
    params:
      manifest: out/manifest.yml
      path: out
